### ISSUE TITLE
New User Agent Header being added on each request

### ISSUE THREAD

**Issue by Simon-Davies** [codewatchorg/Burp-UserAgent#1]
Hi Josh,

I am currently testing your extension with the latest version of Burp and it doesn't seem to be working correctly. It is adding a new user Agent Header on each request in Repeater. See redacted Request below:

GET redacted HTTP/1.1
Host: redacted
User-Agent: Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US) AppleWebKit/532.9 (KHTML, like Gecko) Chrome/5.0.310.0 Safari/532.9
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: redacted
Cookie: PHPSESSID=redacted
Connection: close
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US) AppleWebKit/532.9 (KHTML, like Gecko) Chrome/5.0.310.0 Safari/532.9
User-Agent: Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US) AppleWebKit/532.9 (KHTML, like Gecko) Chrome/5.0.310.0 Safari/532.9
User-Agent: Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US) AppleWebKit/532.9 (KHTML, like Gecko) Chrome/5.0.310.0 Safari/532.9

**Comment by codewatchorg** [comment]
Hmm, I will try to find some time to test this weekend.

**Comment by codewatchorg** [comment]
I tested a fix and pushed at as commit https://github.com/codewatchorg/Burp-UserAgent/commit/4ac775df54eeb8621d66b3de17b92e681f01f59a

This should be fixed now.

**Comment by Simon-Davies** [comment]
Thank you it's fixed. I just looked at the code and can see how you fixed it :)
